In [1]:
import numpy as np

In [2]:
np.sqrt([1,4,9])

array([1., 2., 3.])

In [3]:
np.sqrt([4, -1, -3+4J])

array([2.+0.j, 0.+1.j, 1.+2.j])

In [4]:
np.sqrt([4, -1, np.inf])

C:\Users\User\AppData\Local\Temp\ipykernel_2748\2120485533.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt([4, -1, np.inf])


array([ 2., nan, inf])